### ISSUE TITLE
`http_requests_total` does not exist

### ISSUE THREAD

**Issue by e00E** [prometheus/docs#1074]
The documentation at https://prometheus.io/docs/introduction/first_steps/ uses `http_requests_total` in some examples however this metric does not seem to exist in the current stable version as `http://localhost:9090/metrics` does not include it.

```
prometheus, version 2.3.1 (branch: HEAD, revision: 188ca45bd85ce843071e768d855722a9d9dabe03)
  build user:       root@82ef94f1b8f7
  build date:       20180619-15:56:22
  go version:       go1.10.3
```
Default configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```
```
prometheus --config.file=prometheus.yml
level=info ts=2018-06-20T14:08:53.62998496Z caller=main.go:222 msg="Starting Prometheus" version="(version=2.3.1, branch=HEAD, revision=188ca45bd85ce843071e768d855722a9d9dabe03)"
level=info ts=2018-06-20T14:08:53.630014736Z caller=main.go:223 build_context="(go=go1.10.3, user=root@82ef94f1b8f7, date=20180619-15:56:22)"
level=info ts=2018-06-20T14:08:53.630029531Z caller=main.go:224 host_details="(Linux 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 e(none))"
level=info ts=2018-06-20T14:08:53.630040866Z caller=main.go:225 fd_limits="(soft=1024, hard=1048576)"
level=info ts=2018-06-20T14:08:53.630396033Z caller=main.go:514 msg="Starting TSDB ..."
level=info ts=2018-06-20T14:08:53.630430369Z caller=web.go:415 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-06-20T14:08:53.638679385Z caller=main.go:524 msg="TSDB started"
level=info ts=2018-06-20T14:08:53.638715306Z caller=main.go:603 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-06-20T14:08:53.6392328Z caller=main.go:500 msg="Server is ready to receive web requests."
```
