### ISSUE TITLE
Ensure that all examples work with default metrics

### ISSUE THREAD

**Issue by RichiH** [prometheus/docs#1099]
We are having recurring issues with people stumbling over metric names in examples which do not exist in a default installation of Prometheus, e.g. https://github.com/prometheus/docs/issues/1074 .

@lucperkins is this something you could take?

**Comment by lucperkins** [comment]
@RichiH Sure thing

**Comment by mvalsells** [comment]
The [https://prometheus.io/docs/introduction/first_steps/](https://prometheus.io/docs/introduction/first_steps/) page uses `promhttp_metric_handler_requests_total` as a metric example. However, after installing Prometheus via apt on Ubuntu 18.04 and none configuration changes the metric  `promhttp_metric_handler_requests_total`  dosen't exist in `http://localhost:9090/metrics`, but the `http_requests_total` does.

Kind of oposite of #1074 

```
$ prometheus --version
prometheus, version 2.1.0+ds (branch: debian/sid, revision: 2.1.0+ds-1)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20180121-21:30:42
  go version:       go1.9.3
```
Default config file
```
# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']
```
