### ISSUE TITLE
Routing tree does not support labels with spaces

### ISSUE THREAD

**Issue by TDabasinskas** [prometheus/docs#1201]
Assume we have the following (stripped down) `alertmanager.yml` configuration:

```yaml
receivers:
- name: some-team-email
- name: some-team-sms
- name: another-team-email
- name: default
- name: logger
route:
  group_by:
  - alertname
  routes:
  - receiver: logger
    continue: true
  - match:
      tenant: Some Team
    routes:
    - match:
        severity: warning
      receiver: some-team-email
    - match:
        severity: fatal
      receiver: some-team-sms
  - match:
      tenant: Another Team
    routes:
    - match:
        severity: warning
      receiver: another-team-email
```

Pasting the configuration into [Routing Tree Editor](https://prometheus.io/webtools/alerting/routing-tree-editor/) the graph is drawn correctly.

Anyhow, if I try to test a route with `{tenant="Some Team",severity="warning"}` label matching, I only hit the `logger` receiver, which does not seem to be correct. 

If I update the matcher in the configuration by removing the space inside the tenant name as following, the matcher works and selects the correct route.

```yaml
  - match:
      tenant: SomeTeam
```

It seems that there's an issue with the `routing-tree.js` removing spaces in the label set value.
