### ISSUE TITLE
Prometheus won't read file_sd_config

### ISSUE THREAD

**Issue by swsnider** [prometheus/docs#142]
When I try to load a file_sd_config file, I get no error, but prometheus doesn't show any of those hosts on the status page as candidate for scraping, no matter how long I wait. Nothing is logged, even with -log.level=debug, and promtool doesn't check that file.

included file:

```yaml
targets:
  - host1.example.com:9103
  - host2.example.com:9103
  - host3.example.com:9103
  - host4.example.com:9103
  - host5.example.com:9103
labels:
  - job: zookeeper
```

I'm using this prometheus:
```
prometheus, version 0.15.0rc3 (branch: master, revision: d437fce)
  build user:       swsnider@Silass-Mac-mini.local
  build date:       20150720-16:25:16
  go version:       1.4.2
```

**Comment by swsnider** [comment]
The actual prometheus.yaml is here:

```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  labels:
      cluster: dev
      replica: "1"

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['localhost:9090']

  - file_sd_configs:
    - names:
      - /Users/swsnider/hierasd.yml
    job_name: file_sd
```
