### ISSUE TITLE
Missing explanation for Alerting rules.

### ISSUE THREAD

**Issue by hatosbarbosa** [prometheus/docs#1619]
I've been reading the documentation but couldn't find an explanation of how the following alerting rule expression works:

```
groups:
- name: example
  rules:
  - alert: HighRequestLatency
    expr: **job:request_latency_seconds:mean5m**{job="myjob"} > 0.5
    for: 10m
    labels:
      severity: page
    annotations:
      summary: High request latency
```

It's not explained what does the **"job:"** do in the expression. I've tried running this locally in my prometheus with some metrics but had no answer on how it operates. Can someone please give me an explanation? I can submit a pull request to improve the docs with a thorough description if someone just tell me how does it work.
