### ISSUE TITLE
Add more examples for go templating in alert rules

### ISSUE THREAD

**Issue by Skarlso** [prometheus/docs#1740]
Right now I'm having difficulties setting up conditionals in an alert like this: 

```yaml
    - alert: DiskError
      annotations:
        description: 'The amount of available disk space is low. Current value: {{ $value | humanize }}.'
        runbook_url: 'url'
      expr: data_volume_available_total  / data_volume_total_total <= 0.1
      for: 5m
      labels:
        severity: '{{- if match "server-" $labels.namespace -}} warning {{- else -}} error {{- end -}}'
        category: '{{- if match "server-" $labels.namespace -}} deployment {{- else -}} infrastructure {{- end -}}'
        server_id: '{{- if match "server-" $labels.namespace -}} {{ reReplaceAll "server-(.*)" "$1" $labels.namespace }} {{- else -}} {{- end -}}'
```

I see no reason why this shouldn't work, yet the severity, catergory and server_id field are not interpreted at all. And I can't find any documentation or examples on putting conditionals into the template so I have no idea if this is even possible or not.

Would be nice to add some examples.
