### ISSUE TITLE
Routing tree editor - support new matchers syntax

### ISSUE THREAD

**Issue by cinatic** [prometheus/docs#1965]
When testing with the latest example the editor is showing the wrong matched route

https://prometheus.io/docs/alerting/latest/configuration/#example

**Comment by mattpr** [comment]
# repro

Go here: https://prometheus.io/webtools/alerting/routing-tree-editor/

## "Alertmanager config.yml" text area

```yaml
route:
  receiver: default
  routes:
    - receiver: customer01
      matchers:
      - instance=~".*\\.cus01\\.example\\.com:[0-9]+$|.*customer01\\..*"
      continue: true   # continue so default receiver also gets these notifications
    - receiver: customer02
      matchers:
      - instance=~".*\\.cus02\\.example\\.com:[0-9]+$|.*customer02\\..*"
      continue: true   # continue so default receiver also gets these notifications
```

## "Match Label Set" box
```
{instance="some.host.cus01.example.com:9100"}
```

## Steps

- go to the routing tree editor page
- paste the above alertmanager config and example labels into the corresponding boxes
- click "draw routing tree" button.  Observe routing tree is drawn as expected.
- click the "match label set" button.  observe that according to the routing tree editor, both leaf routes match.

### What is expected

When clicking "match label set" button, only the matching routes should be highlighted.
This indicates that this debug/testing tool is not compatible with the new `matchers` syntax.

**Comment by mattpr** [comment]
There is a second issue with this tool.  If you only have a single route (besides the default) the tool errors.

Example config...

```yaml
route:
  receiver: default
  routes:
    - receiver: customer01
      matchers:
      - instance=~".*\\.cus01\\.example\\.com:[0-9]+$|.*customer01\\..*"
      continue: true   # continue so default receiver also gets these notifications
```

gives a bunch of d3js errors in the browser console (`d3.v3.min.js:1 Error: <g> attribute transform: Expected number, "rotate(NaN)translate(45…`) and the rendering of the route is unreadable.
