### ISSUE TITLE
Prometheus as data source in Grafana

### ISSUE THREAD

**Issue by miparnisari** [prometheus/docs#2237]
https://github.com/prometheus/docs/blob/8d0bcf464f6275a544b15b7c214e9092fcb145b0/content/docs/guides/go-application.md?plain=1#L23

After following this guide, i have Prometheus data at `http://localhost:2112/metrics`.

However, if I try to add Prometheus as a data source in Grafana, Grafana tries to query `api/v1/query`, which doesn't have anything.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/5374887/202334121-6aca68c5-2af0-45b6-994a-c6ae75613616.png">

What am I missing?

**Comment by miparnisari** [comment]
okay i figured it out, i think this is worth documenting.

In my Docker compose file:

```
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - default
    ports:
      - "3000:3000"
```

In my app code:

```go
		go func() {
			logger.Info("🔬 starting prometheus on localhost:2112")
			http.Handle("/metrics", promhttp.Handler())
			http.ListenAndServe(":2112", nil)
		}()
```

In my prometheus.yml file:

```
scrape_configs:
  - job_name: 'scrape'
    static_configs:
      - targets: ['host.docker.internal:2112']
```
