### ISSUE TITLE
Freeze releases structure

### ISSUE THREAD

**Issue by hryamzik** [prometheus/docs#447]
Can I possibly ask you to stop moving files in releases archives? I've written some automation that takes linux 64 bit archive from the latest guthub release and extracts it to FS.

Recently ```node_exporter``` just contained the ```node_exporter``` binary, now it's the ```node_exporter-0.12.0.linux-amd64``` directory.

**Comment by hryamzik** [comment]
Thanks, and can I relay on ```linux-amd64``` substring in linux 64 archives?

```
- name: get package url
  set_fact:
      prometheus_json: "{{ item }}"
  with_items: github_release.assets
  when: "'linux-amd64' in item.name"
```
