### ISSUE TITLE
What is the correct formatting for alert rules?

### ISSUE THREAD

**Issue by pajtai** [prometheus/docs#907]
I see two different formats for alert rules:

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
https://prometheus.io/docs/alerting/rules/

I don't understand whether these are two different formats that are both correct and one is used in a yml file and one is used in an imported rules file, or if only one is correct.

https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/ has the format:

```
groups:
- name: example
  rules:
  - alert: HighErrorRate
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 10m
    labels:
      severity: page
    annotations:
      summary: High request latency
```

while https://prometheus.io/docs/alerting/rules/ has the format:

```
ALERT <alert name>
  IF <expression>
  [ FOR <duration> ]
  [ LABELS <label set> ]
  [ ANNOTATIONS <label set> ]
```
