### ISSUE TITLE
Gettings started config returns no data

### ISSUE THREAD

**Issue by k** [prometheus/docs#958]
Versions: 2.1.0
Platform: Darwin (mac os 10.13.2)

## config file
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
```
The same one listed on https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-itself

After starting the server, when I go to localhost:9090/graphs, it says there is no data
